# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 5

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
#    - build: VisualStudio (x32)
#      name: VisualStudio
#      generator: VisualStudio-x32
#      extension: bat
#      command: cmd
#    - build: VisualStudio (x64)
#      name: VisualStudio
#      generator: VisualStudio-x64
#      extension: bat
#      command: cmd
    - build: Cygwin (x32)
      name: Cygwin
      generator: Cygwin
      extension: sh
      command: C:\cygwin\bin\bash -lc
    - build: Cygwin (x64)
      name: Cygwin
      generator: Cygwin
      extension: sh
      command: C:\cygwin64\bin\bash -lc

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - if "%name%"=="VisualStudio" msbuild /version
  - if "%name%"=="Cygwin" %command% "cygcheck -dc cygwin"
  - cmake --version

# Scripts that run after cloning repository
install:
  - if "%name%"=="VisualStudio (x32)" choco install doxygen.portable
  - if "%name%"=="VisualStudio (x64)" choco install doxygen.portable
  - git config --global user.name "AppVeyor"
  - git config --global user.email "team@appveyor.com"
  - git config --global push.default simple
  - git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cd scripts
  - 01-generate-%generate%.%ext%
  - 02-build-%name%.%ext%
  - 03-tests.%ext%
  - 04-install-%name%.%ext%
  - 05-doxygen-%name%.%ext%
  - 06-clean.%ext%

# Test scripts
test: off
