# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 5

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
#    - build: VisualStudio
#      ext: bat
#      command: cmd /C
#      prefix:
#    - build: Cygwin
#      ext: sh
#      command: C:\cygwin64\bin\bash -lc
#      prefix: cd $APPVEYOR_BUILD_FOLDER/scripts; exec 0</dev/null;
    - build: MinGW
      ext: bat
      command: cmd /C
      prefix:

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - if "%build%"=="VisualStudio" msbuild /version
  - if "%build%"=="Cygwin" %command% "cygcheck -dc cygwin"
  - '%command% "cmake --version"'
  - '%command% "git config --global user.name "AppVeyor""'
  - '%command% "git config --global user.email "team@appveyor.com""'
  - '%command% "git config --global push.default simple"'

# Scripts that run after cloning repository
install:
  - if "%build%"<>"Cygwin" choco install doxygen.portable
  - if "%build%"<>"Cygwin" choco install graphviz.portable
  - if "%build%"=="Cygwin" C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --root "C:\cygwin64" --local-package-dir "C:\cygwin64\var\cache\setup" --packages doxygen,graphviz
  - if "%build%"=="MinGW" set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
  - '%command% "%prefix% git submodule update --init --recursive --remote"'

# Cache Cygwin files to speed up build
cache:
    - 'C:\cygwin64\var\cache\setup'

# Build scripts
build_script:
  - cd scripts
  - ren "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe
  - '%command% "%prefix% ./01-generate-%build%.%ext%"'
  - ren "C:\Program Files\Git\usr\bin\_sh.exe" sh.exe
  - '%command% "%prefix% ./02-build-%build%.%ext%"'
  - '%command% "%prefix% ./03-tests.%ext%"'
  - '%command% "%prefix% ./04-install-%build%.%ext%"'
  - '%command% "%prefix% ./05-doxygen-%build%.%ext%"'
  - '%command% "%prefix% ./06-clean.%ext%"'

# Test scripts
test: off
