# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 5

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
#    - build: VisualStudio (x32)
#      command: cmd
#      generate: VisualStudio-x32
#      name: VisualStudio
#      ext: bat
#    - build: VisualStudio (x64)
#      command: cmd
#      generate: VisualStudio-x64
#      name: VisualStudio
#      ext: bat
    - build: Cygwin (x32)
      command: C:\cygwin\bin\bash -lc
      generate: Cygwin
      name: Cygwin
      ext: sh
    - build: Cygwin (x64)
      command: C:\cygwin64\bin\bash -lc
      generate: Cygwin
      name: Cygwin
      ext: sh

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - if "%build%"=="VisualStudio (x32)" %command% "msbuild /version"
  - if "%build%"=="VisualStudio (x64)" %command% "msbuild /version"
  - if "%build%"=="Cygwin (x32)" %command% "cygcheck -dc cygwin"
  - if "%build%"=="Cygwin (x64)" %command% "cygcheck -dc cygwin"
  - %command% "cmake  --version"

# Scripts that run after cloning repository
install:
  - if "%build%"=="VisualStudio (x32)" choco install doxygen.portable
  - if "%build%"=="VisualStudio (x32)" choco install graphviz.portable
  - if "%build%"=="VisualStudio (x64)" choco install doxygen.portable
  - if "%build%"=="VisualStudio (x64)" choco install graphviz.portable
  - git config --global user.name "AppVeyor"
  - git config --global user.email "team@appveyor.com"
  - git config --global push.default simple
  - git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cd scripts
  - 01-generate-%generate%.%ext%
  - 02-build-%name%.%ext%
  - 03-tests.%ext%
  - 04-install-%name%.%ext%
  - 05-doxygen-%name%.%ext%
  - 06-clean.%ext%

# Test scripts
test: off
