language: cpp

os:
- linux
- osx

sudo: required
dist: trusty

compiler:
- gcc

addons:
  apt:
    packages:
    - cmake
    - doxygen
    - graphviz

before_install:
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

script: 
- cd ./scripts
- ./01-generate-Unix.sh
- ./02-build-Unix.sh
- ./03-tests.sh
- ./04-install-Unix.sh
- ./05-doxygen-Unix.sh
- ./06-clean.sh

branches:
  only:
  - master
